openapi: 3.1.0
info:
  description: |
    This is a sample server for sphinx-relay below you'll find api docs and such

  version: 1.0.0
  title: Swagger Sphinx-Relay
  summary: My lovely API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Sphinx Support
    email: support@stakwork.com
  x-logo:
    url: 'https://miro.medium.com/max/512/1*sAlVjz09nS6f7iYJ6apMhg.png'
    altText: Sphinx-Chat logo
  license:
    name: MIT License
    url: 'https://raw.githubusercontent.com/stakwork/sphinx-relay/master/LICENSE'
    identifier: MIT License
tags:
  - name: tribes
    description: Everything about your Tribes
  - name: store_model
    x-displayName: The Order Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Order" exampleRef="#/components/examples/Order" showReadOnly={true} showWriteOnly={true} />
x-tagGroups:
  - name: Tribes
    tags:
      - tribe_channel
      - tribes
  - name: Models
    tags:
      - pet_model
      - store_model
paths:
  /tribe_channel:
    parameters:
      - name: x-user-token
        in: header
        description: "this is a token that is used to authenticate the correct user is accesing the relay"
        example: QoiCvW84+Q0E77+wysfj
        required: true
        schema:
          type: string
          default: none
    post:
      tags:
        - tribe_channel
      summary: Add a new channel for tribe in tribe server
      description: Create new tribe text channel.
      operationId: addPet
      responses:
        '405':
          description: Invalid input
      security:
        - authToken:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                tribe_uuid:
                  description: The id of the tribe to add channel to.
                  type: string
                host:
                  description: the domain of the host tribe server.
                  type: string
                name:
                  type: string
              type: object
  securitySchemes:
    x-auth-token:
      description: |
        This is for accessing your relay, recommended to use x-transport-token instead.
      type: ???
      in: header
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/api/oauth/dialog'
          scopes:
            'write:pets': modify pets in your account
            'read:pets': read your pets
    x-transport-token:
      description: >
        encrypts x-auth-token with the x-transport-token pubkey with timestamp.
      type: ???
      in: header
  examples:
    Order:
      value:
        quantity: 1
        shipDate: '2018-10-19T16:46:45Z'
        status: placed
        complete: false
