name: Push
on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Enable docker.host.internal for Ubuntu
      run: |
        sudo bash -c 'echo "172.17.0.1 host.docker.internal" >> /etc/hosts'
    - uses: actions/checkout@v2
      with:
        name: kevkevinpal/sphinx-relay      
        path: relay
        branch: stackOnDrone
    - name: Build Relay
      working-directory: ./relay
      run: |
        npm install --dev && npm run build && docker build -t kevkevinpal/sphinx-relay . 
    - name: Checkout stack
      run: |
        git clone -b relayPRTesting https://github.com/kevkevinpal/sphinx-stack.git stack
    - name: give permissions 
      working-directory: ./stack
      run: |
        chmod 777 ./bitcoind     
    - name: Turn on Stack 
      working-directory: ./stack
      run: |
        sudo docker-compose up -d 
    - name: Check for NODES.json
      working-directory: ./stack
      run: |
         sleep 120;
         docker logs stack_relaysetup_1;
         docker logs alice.sphinx;
         docker ps;
         docker logs alice.sphinx;
         docker logs db.sphinx;
         docker restart alice.sphinx;
         sleep 40;
         docker ps;
         docker logs db.sphinx;
         docker wait stack_relaysetup_1 
    - name: Run tests
      working-directory: ./relay
      run: |
        npm run test
        #;  cat ./relay/NODES.json;  cp ./relay/NODES.json ../relay/src/tests/configs/nodes.json
