name: Push
on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: macos-latest
    steps:
            #    - uses: actions/checkout@v2
            #      with:
            #        path: relay
            #    - name: Build Relay
            #      run: |
            #        cd ./relay && docker build -t sphinxlightning/sphinx-relay-test .
    - uses: actions/checkout@v2
      with:
        name: stakwork/sphinx-stack
        path: stack
    - name: Docker stack 
      run: |
        cd ./stack && ls -a && docker-compose pull && docker-compose up -d

