name: Push
on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        name: kevkevinpal/sphinx-relay      
        path: relay
        branch: stackOnDrone
    - name: Build Relay
      run: |
        cd ./relay && npm install --dev && docker build -t sphinxlightning/sphinx-relay-test .
    - uses: actions/checkout@v2
      with:
        name: stakwork/sphinx-stack
        path: stack
    - name: Docker stack 
      run: |
        cd ../stack && ls -a && docker-compose pull && docker-compose up -d
    - name: Run tests
      run: |
        cd ../relay && npm run test
