name: Push
on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-18.04 
    steps:
    - name: Enable docker.host.internal for Ubuntu
      run: |
        pwd && sudo bash -c 'echo "172.17.0.1 host.docker.internal" >> /etc/hosts'
    - uses: actions/checkout@v2
      with:
        name: kevkevinpal/sphinx-relay      
        path: relay
        branch: stackOnDrone
    - name: Build Relay
      working-directory: ./relay
      run: |
        npm install --dev && npm run build && docker build -t kevkevinpal/sphinx-relay . 
    - name: Checkout stack
      run: |
        git clone -b relayPRTesting https://github.com/kevkevinpal/sphinx-stack.git stack
    - name: give permissions 
      working-directory: ./stack
      run: |
        chmod 777 ./bitcoind;    
        chmod 777 ./relay;
    - name: Turn on Stack 
      working-directory: ./stack
      run: |
        sudo docker-compose up -d 
    - name: Check for NODES.json
      working-directory: ./stack
      run: |
         sleep 120;
         docker ps;
         docker logs alice.sphinx;
         docker-compose ps;
         docker wait stack_relaysetup_1;
         mkdir ../relay/src/tests/configs/;
         touch ../relay/src/tests/configs/nodes.json;
         ls ../relay/src/tests/configs;
         #touch ../relay/src/tests/configs/nodes.json
         #sudo cp ./relay/NODES.json ../relay/src/tests/configs/nodes.json;
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "stack/relay/NODES.json"
        target: "relay/src/tests/configs/nodes.json"     
    - name: Run tests
      working-directory: ./relay
      run: |
        npx ava src/tests/controllers/paidMeet.test.ts --verbose --serial --timeout=2m
        #npm run test
        #;  cat ./relay/NODES.json;  cp ./relay/NODES.json ../relay/src/tests/configs/nodes.json
