name: Push
on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Relay
      run: |
        docker build -t sphinxlightning .
    - uses: actions/checkout@v2
      with:
        name: stakwork/sphinx-stack
    - name: Cloning Stack
      run: |
        docker-compose up -d

