name: Push
on: [pull_request]
  branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Relay
      run: |
        docker build -t sphinxlightning .
    - uses: actions/checkout@v2
      name: Cloning Stack
      with:
        name: stakwork/sphinx-stack
      run: |
        docker-compose up -d

