name: Push
on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: relay
    - name: Build Relay
      run: |
        cd ./relay && docker build -t sphinxlightning .
    - uses: actions/checkout@v2
      with:
        name: stakwork/sphinx-stack
        path: stack
    - name: Cloning Stack
      run: |
        cd ./stack && docker-compose up -d

