name: Pull_Request 
on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-18.04 
    steps:
    - name: Enable docker.host.internal for Ubuntu
      run: |
        pwd && sudo bash -c 'echo "172.17.0.1 host.docker.internal" >> /etc/hosts'
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: relay
    - name: Build Relay
      working-directory: ./relay
      run: |
        npm install && npm run build && docker build -t sphinxlightninggitactionenv/sphinx-relay . 
    - name: Checkout stack
      run: |
        git clone -b relayPRTesting https://github.com/kevkevinpal/sphinx-stack.git stack
    - name: give permissions 
      working-directory: ./stack
      run: |
        chmod 777 ./bitcoind;    
    - name: Turn on Stack 
      working-directory: ./stack
      run: |
        docker images;
        GITACTION_ENV=gitactionenv docker-compose up -d 
    - name: Check for NODES.json
      working-directory: ./stack
      run: |
         sleep 120;
         docker wait stack_relaysetup_1;
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "stack/relay/NODES.json"
        target: "relay/src/tests/configs/nodes.json"     
    - name: Run tests
      working-directory: ./relay
      run: |
        npx ava src/tests/controllers/boostPayment.test.ts --verbose --serial --timeout=2m
        #npx ava src/tests/controllers/chatInvoice.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/botCreation.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/chatPayment.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/cleanup.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/clearAllChats.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/clearAllContacts.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/contacts.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/images.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/latestTest.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/lsats.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/paidMeet.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/paidTribeImages.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/queryRoutes.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/self.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/sphinxPeople.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/streamPayment.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/tribe.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/tribe3Escrow.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/tribe3Messages.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/tribe3Private.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/tribe3Profile.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/tribeEdit.test.ts --verbose --serial --timeout=2m &&
        #npx ava src/tests/controllers/tribeImages.test.ts --verbose --serial --timeout=2m
